# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deployment

# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - Test
        - Production
      imageVersion:
        description: 'Version'
        required: false
        default: 'dev'
        type: string
  workflow_run:
    workflows: [Official]
    types: [completed]
    branches: [dev]

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  IMAGE_NAME: syzero.blog.admin
  IMAGE_VERSION: dev
  ENVIRONMENT: Test
  CONTAINER_NAME: syzero.blog.admin
  CONTAINER_PORT: 7005
  CONTAINER_TEST_PORT: 8005
  CONTAINER_PROD_PORT: 7005

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: initialization 
        run: |
          imageVersion=${{ env.IMAGE_VERSION }}
          environment=${{ env.ENVIRONMENT }}
          if [ "${{ inputs.imageVersion }}" != "" ]; then
            echo "IMAGE_VERSION=${{ inputs.imageVersion }}" >> $GITHUB_ENV
            imageVersion=${{ inputs.imageVersion }}
          fi
          if [ "${{ inputs.environment }}" != "" ]; then
            echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
            environment=${{ inputs.environment }}
          fi
          if [ "$environment" == "Production" ]; then
            echo "CONTAINER_PORT=${{ env.CONTAINER_PROD_PORT }}" >> $GITHUB_ENV
          fi
          if [ "$environment" == "Test" ]; then
            echo "CONTAINER_PORT=${{ env.CONTAINER_TEST_PORT }}" >> $GITHUB_ENV
            echo "CONTAINER_NAME=${{ env.CONTAINER_NAME }}-test" >> $GITHUB_ENV
          fi

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          script: |
            docker login harbor.syzero.com -u '${{ secrets.HARBOR_DOCKERHUB_USERNAME }}' -p '${{ secrets.HARBOR_DOCKERHUB_TOKEN }}'
            docker stop ${{ env.CONTAINER_NAME }}
            docker rm ${{ env.CONTAINER_NAME }}
            docker pull harbor.syzero.com/syzero/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            docker run -d -p ${{ env.CONTAINER_PORT }}:80 --name=${{ env.CONTAINER_NAME }} --restart=always -e "UI_ENVIRONMENT=${{ env.ENVIRONMENT }}" --network "SyZero-${{ env.ENVIRONMENT }}" harbor.syzero.com/syzero/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}