# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Official

# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: 
  push:
    branches: [ "master", "dev" ]

env:
  GB_NUGET_TOKEN: ${{secrets.GB_NUGET_TOKEN}}
  MS_NUGET_TOKEN: ${{secrets.MS_NUGET_TOKEN}}
  SYZERO_CORE_BRANCH: dev1.1.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ./dist/*
            ./Dockerfile

  pushImage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: harbor.syzero.com
          username: ${{ secrets.HARBOR_DOCKERHUB_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKERHUB_TOKEN }}

      - name: Build and push (master)
        uses: docker/build-push-action@v4
        if: github.ref_name == 'master'
        with:
          context: ./
          push: true
          tags: |
            harbor.syzero.com/syzero/syzero.blog.admin:latest
            harbor.syzero.com/syzero/syzero.blog.admin:${{ github.run_number }}

      - name: Build and push (dev)
        uses: docker/build-push-action@v4
        if: github.ref_name == 'dev'
        with:
          context: ./
          push: true
          tags: |
            harbor.syzero.com/syzero/syzero.blog.admin:dev
            harbor.syzero.com/syzero/syzero.blog.admin:${{ github.run_number }}-dev